exclude: ^(docs|examples|.github|doped/pycdt/test_files|tests/data)
repos:
  # Lint and format, isort, docstrings...
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff
        args: [--fix]

  # Remove trailing whitespace, leave empty line at end of file
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black  # max line length 107 specified in pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy

  # Check typos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        stages: [commit,commit-msg]
        exclude_types: [html]
        additional_dependencies: [tomli] # needed to read pyproject.toml for python < 3.11

  # format docstring length:
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.1
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place,--config,./pyproject.toml]
